name: Beta manual workflow-Integration

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
        
jobs: 
  deploy:
    # The type of runner that the job will run on  
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
   
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: copy file via ssh password
        uses: appleboy/ssh-action@master
        with:
          host: integration.palm-tech.com
          username: root  
          password: ${{ secrets.ROOT_PASSWORD }}
          port: 22
          script: 'cd /home/jsingh/tmp/demo && ./server_deploy.sh'
    
