name: Beta manual workflow-Integration

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
        
jobs: 
  deploy:
    # The type of runner that the job will run on  
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
   
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Integration-Deploy-Action
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'jsingh'
          server: 'integration.palm-tech.com'
          ssh_private_key: ${{ secrets.INT_PASSWORD }}
          local_path: '.'
          remote_path: 'tmp/M-Integration/public_html'
          args: '-o ConnectTimeout=5'
