name: Manual workflow-Integration-Manual

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
        
jobs: 
  deploy:
    # The type of runner that the job will run on  
    runs-on: ubuntu-latest
    inputs:
      server:
        description: 'Server to deploy: Intergration or Cloud-C or Production'
        # Default value if no value is explicitly provided
        default: 'Intergration'
        # Input has to be provided for the workflow to run
        required: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Deploy to Integration
      uses: garygrossgarten/github-action-scp@release
      with:
          local: ./
          remote: tmp/M-Integration/public_html
          host: integration.palm-tech.com
          username: jsingh
          password: ${{ secrets.INT_PASSWORD }}
   
