name: Full manual workflow-Integration

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
        
jobs: 
  deploy:
    # The type of runner that the job will run on  
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
   
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Deploy to Integration
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./
          remote: tmp/M-Integration/public_html
          host: integration.palm-tech.com
          username: jsingh
          password: ${{ secrets.INT_PASSWORD }}
   
