name: Manual workflow-Prod

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
        
jobs: 
  deploy:
    # The type of runner that the job will run on  
    runs-on: ubuntu-latest
    environment: Production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Deploy to Production
      uses: garygrossgarten/github-action-scp@release
      with:
          local: ./
          remote: tmp/Production/public_html
          host: integration.palm-tech.com
          username: jsingh
          password: ${{ secrets.PROD_PASSWORD }}
    - name: Directory Permissions
      run: chmod -R 777 hello.html
